remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap